AZURE_LOCATION: 'centralindia'
RESOURCE_NAME_PREFIX: 'apimdemo'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'salils3211'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'
